/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppDealerRouteImport } from './routes/_authenticated/app.dealer'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app.marketplace'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppPassportRouteImport } from './routes/_authenticated/app.passport'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppReportRouteImport } from './routes/_authenticated/app.report'
import { Route as AuthenticatedAppReputationRouteImport } from './routes/_authenticated/app.reputation'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppShopRouteImport } from './routes/_authenticated/app.shop'
import { Route as AuthenticatedAppSupplierRouteImport } from './routes/_authenticated/app.supplier'
import { Route as AuthenticatedAppJobIdRouteImport } from './routes/_authenticated/app.job.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDealerRoute = AuthenticatedAppDealerRouteImport.update({
  id: '/app/dealer',
  path: '/app/dealer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/app/marketplace',
    path: '/app/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/app/orders',
  path: '/app/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPassportRoute =
  AuthenticatedAppPassportRouteImport.update({
    id: '/app/passport',
    path: '/app/passport',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppReportRoute = AuthenticatedAppReportRouteImport.update({
  id: '/app/report',
  path: '/app/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppReputationRoute =
  AuthenticatedAppReputationRouteImport.update({
    id: '/app/reputation',
    path: '/app/reputation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/app/services',
    path: '/app/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppShopRoute = AuthenticatedAppShopRouteImport.update({
  id: '/app/shop',
  path: '/app/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSupplierRoute =
  AuthenticatedAppSupplierRouteImport.update({
    id: '/app/supplier',
    path: '/app/supplier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppJobIdRoute = AuthenticatedAppJobIdRouteImport.update({
  id: '/app/job/$id',
  path: '/app/job/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/offline': typeof OfflineRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/dealer': typeof AuthenticatedAppDealerRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/passport': typeof AuthenticatedAppPassportRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/reputation': typeof AuthenticatedAppReputationRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/app/supplier': typeof AuthenticatedAppSupplierRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/job/$id': typeof AuthenticatedAppJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/offline': typeof OfflineRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/dealer': typeof AuthenticatedAppDealerRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/passport': typeof AuthenticatedAppPassportRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/reputation': typeof AuthenticatedAppReputationRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/app/supplier': typeof AuthenticatedAppSupplierRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/job/$id': typeof AuthenticatedAppJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/offline': typeof OfflineRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/dealer': typeof AuthenticatedAppDealerRoute
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/passport': typeof AuthenticatedAppPassportRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/report': typeof AuthenticatedAppReportRoute
  '/_authenticated/app/reputation': typeof AuthenticatedAppReputationRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/shop': typeof AuthenticatedAppShopRoute
  '/_authenticated/app/supplier': typeof AuthenticatedAppSupplierRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/job/$id': typeof AuthenticatedAppJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/offline'
    | '/services'
    | '/admin'
    | '/app/admin'
    | '/app/dealer'
    | '/app/marketplace'
    | '/app/orders'
    | '/app/passport'
    | '/app/profile'
    | '/app/report'
    | '/app/reputation'
    | '/app/services'
    | '/app/shop'
    | '/app/supplier'
    | '/app/'
    | '/app/job/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/offline'
    | '/services'
    | '/admin'
    | '/app/admin'
    | '/app/dealer'
    | '/app/marketplace'
    | '/app/orders'
    | '/app/passport'
    | '/app/profile'
    | '/app/report'
    | '/app/reputation'
    | '/app/services'
    | '/app/shop'
    | '/app/supplier'
    | '/app'
    | '/app/job/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/marketplace'
    | '/offline'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/dealer'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/passport'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/report'
    | '/_authenticated/app/reputation'
    | '/_authenticated/app/services'
    | '/_authenticated/app/shop'
    | '/_authenticated/app/supplier'
    | '/_authenticated/app/'
    | '/_authenticated/app/job/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OfflineRoute: typeof OfflineRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dealer': {
      id: '/_authenticated/app/dealer'
      path: '/app/dealer'
      fullPath: '/app/dealer'
      preLoaderRoute: typeof AuthenticatedAppDealerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/app/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/app/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/passport': {
      id: '/_authenticated/app/passport'
      path: '/app/passport'
      fullPath: '/app/passport'
      preLoaderRoute: typeof AuthenticatedAppPassportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/report': {
      id: '/_authenticated/app/report'
      path: '/app/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AuthenticatedAppReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/reputation': {
      id: '/_authenticated/app/reputation'
      path: '/app/reputation'
      fullPath: '/app/reputation'
      preLoaderRoute: typeof AuthenticatedAppReputationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/shop': {
      id: '/_authenticated/app/shop'
      path: '/app/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AuthenticatedAppShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/supplier': {
      id: '/_authenticated/app/supplier'
      path: '/app/supplier'
      fullPath: '/app/supplier'
      preLoaderRoute: typeof AuthenticatedAppSupplierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/job/$id': {
      id: '/_authenticated/app/job/$id'
      path: '/app/job/$id'
      fullPath: '/app/job/$id'
      preLoaderRoute: typeof AuthenticatedAppJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppDealerRoute: typeof AuthenticatedAppDealerRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppPassportRoute: typeof AuthenticatedAppPassportRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReportRoute: typeof AuthenticatedAppReportRoute
  AuthenticatedAppReputationRoute: typeof AuthenticatedAppReputationRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppShopRoute: typeof AuthenticatedAppShopRoute
  AuthenticatedAppSupplierRoute: typeof AuthenticatedAppSupplierRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppJobIdRoute: typeof AuthenticatedAppJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppDealerRoute: AuthenticatedAppDealerRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppPassportRoute: AuthenticatedAppPassportRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReportRoute: AuthenticatedAppReportRoute,
  AuthenticatedAppReputationRoute: AuthenticatedAppReputationRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppShopRoute: AuthenticatedAppShopRoute,
  AuthenticatedAppSupplierRoute: AuthenticatedAppSupplierRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppJobIdRoute: AuthenticatedAppJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  OfflineRoute: OfflineRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
